/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSalesRouteImport } from './routes/app.sales'
import { Route as AppRequestsRouteImport } from './routes/app.requests'
import { Route as AppPackagesRouteImport } from './routes/app.packages'
import { Route as AppNetworksRouteImport } from './routes/app.networks'
import { Route as AppManageCardsRouteImport } from './routes/app.manage-cards'
import { Route as AppLogsRouteImport } from './routes/app.logs'
import { Route as AppJoinRequestsRouteImport } from './routes/app.join-requests'
import { Route as AppCardsRouteImport } from './routes/app.cards'
import { Route as AppCabinRouteImport } from './routes/app.cabin'
import { Route as AppAgentsRouteImport } from './routes/app.agents'
import { Route as AppAgentAccountsRouteImport } from './routes/app.agent-accounts'
import { Route as AppNetworksIndexRouteImport } from './routes/app.networks.index'
import { Route as AppNetworksIdRouteImport } from './routes/app.networks.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppPackagesRoute = AppPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworksRoute = AppNetworksRouteImport.update({
  id: '/networks',
  path: '/networks',
  getParentRoute: () => AppRoute,
} as any)
const AppManageCardsRoute = AppManageCardsRouteImport.update({
  id: '/manage-cards',
  path: '/manage-cards',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppJoinRequestsRoute = AppJoinRequestsRouteImport.update({
  id: '/join-requests',
  path: '/join-requests',
  getParentRoute: () => AppRoute,
} as any)
const AppCardsRoute = AppCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AppRoute,
} as any)
const AppCabinRoute = AppCabinRouteImport.update({
  id: '/cabin',
  path: '/cabin',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentAccountsRoute = AppAgentAccountsRouteImport.update({
  id: '/agent-accounts',
  path: '/agent-accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworksIndexRoute = AppNetworksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppNetworksRoute,
} as any)
const AppNetworksIdRoute = AppNetworksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppNetworksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/agent-accounts': typeof AppAgentAccountsRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/cabin': typeof AppCabinRoute
  '/app/cards': typeof AppCardsRoute
  '/app/join-requests': typeof AppJoinRequestsRoute
  '/app/logs': typeof AppLogsRoute
  '/app/manage-cards': typeof AppManageCardsRoute
  '/app/networks': typeof AppNetworksRouteWithChildren
  '/app/packages': typeof AppPackagesRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/networks/$id': typeof AppNetworksIdRoute
  '/app/networks/': typeof AppNetworksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/agent-accounts': typeof AppAgentAccountsRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/cabin': typeof AppCabinRoute
  '/app/cards': typeof AppCardsRoute
  '/app/join-requests': typeof AppJoinRequestsRoute
  '/app/logs': typeof AppLogsRoute
  '/app/manage-cards': typeof AppManageCardsRoute
  '/app/packages': typeof AppPackagesRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/networks/$id': typeof AppNetworksIdRoute
  '/app/networks': typeof AppNetworksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/agent-accounts': typeof AppAgentAccountsRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/cabin': typeof AppCabinRoute
  '/app/cards': typeof AppCardsRoute
  '/app/join-requests': typeof AppJoinRequestsRoute
  '/app/logs': typeof AppLogsRoute
  '/app/manage-cards': typeof AppManageCardsRoute
  '/app/networks': typeof AppNetworksRouteWithChildren
  '/app/packages': typeof AppPackagesRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/networks/$id': typeof AppNetworksIdRoute
  '/app/networks/': typeof AppNetworksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/agent-accounts'
    | '/app/agents'
    | '/app/cabin'
    | '/app/cards'
    | '/app/join-requests'
    | '/app/logs'
    | '/app/manage-cards'
    | '/app/networks'
    | '/app/packages'
    | '/app/requests'
    | '/app/sales'
    | '/app/settings'
    | '/app/'
    | '/app/networks/$id'
    | '/app/networks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/agent-accounts'
    | '/app/agents'
    | '/app/cabin'
    | '/app/cards'
    | '/app/join-requests'
    | '/app/logs'
    | '/app/manage-cards'
    | '/app/packages'
    | '/app/requests'
    | '/app/sales'
    | '/app/settings'
    | '/app'
    | '/app/networks/$id'
    | '/app/networks'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/agent-accounts'
    | '/app/agents'
    | '/app/cabin'
    | '/app/cards'
    | '/app/join-requests'
    | '/app/logs'
    | '/app/manage-cards'
    | '/app/networks'
    | '/app/packages'
    | '/app/requests'
    | '/app/sales'
    | '/app/settings'
    | '/app/'
    | '/app/networks/$id'
    | '/app/networks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales': {
      id: '/app/sales'
      path: '/sales'
      fullPath: '/app/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requests': {
      id: '/app/requests'
      path: '/requests'
      fullPath: '/app/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/packages': {
      id: '/app/packages'
      path: '/packages'
      fullPath: '/app/packages'
      preLoaderRoute: typeof AppPackagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/networks': {
      id: '/app/networks'
      path: '/networks'
      fullPath: '/app/networks'
      preLoaderRoute: typeof AppNetworksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/manage-cards': {
      id: '/app/manage-cards'
      path: '/manage-cards'
      fullPath: '/app/manage-cards'
      preLoaderRoute: typeof AppManageCardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logs': {
      id: '/app/logs'
      path: '/logs'
      fullPath: '/app/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/join-requests': {
      id: '/app/join-requests'
      path: '/join-requests'
      fullPath: '/app/join-requests'
      preLoaderRoute: typeof AppJoinRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cards': {
      id: '/app/cards'
      path: '/cards'
      fullPath: '/app/cards'
      preLoaderRoute: typeof AppCardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cabin': {
      id: '/app/cabin'
      path: '/cabin'
      fullPath: '/app/cabin'
      preLoaderRoute: typeof AppCabinRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agents': {
      id: '/app/agents'
      path: '/agents'
      fullPath: '/app/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agent-accounts': {
      id: '/app/agent-accounts'
      path: '/agent-accounts'
      fullPath: '/app/agent-accounts'
      preLoaderRoute: typeof AppAgentAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/networks/': {
      id: '/app/networks/'
      path: '/'
      fullPath: '/app/networks/'
      preLoaderRoute: typeof AppNetworksIndexRouteImport
      parentRoute: typeof AppNetworksRoute
    }
    '/app/networks/$id': {
      id: '/app/networks/$id'
      path: '/$id'
      fullPath: '/app/networks/$id'
      preLoaderRoute: typeof AppNetworksIdRouteImport
      parentRoute: typeof AppNetworksRoute
    }
  }
}

interface AppNetworksRouteChildren {
  AppNetworksIdRoute: typeof AppNetworksIdRoute
  AppNetworksIndexRoute: typeof AppNetworksIndexRoute
}

const AppNetworksRouteChildren: AppNetworksRouteChildren = {
  AppNetworksIdRoute: AppNetworksIdRoute,
  AppNetworksIndexRoute: AppNetworksIndexRoute,
}

const AppNetworksRouteWithChildren = AppNetworksRoute._addFileChildren(
  AppNetworksRouteChildren,
)

interface AppRouteChildren {
  AppAgentAccountsRoute: typeof AppAgentAccountsRoute
  AppAgentsRoute: typeof AppAgentsRoute
  AppCabinRoute: typeof AppCabinRoute
  AppCardsRoute: typeof AppCardsRoute
  AppJoinRequestsRoute: typeof AppJoinRequestsRoute
  AppLogsRoute: typeof AppLogsRoute
  AppManageCardsRoute: typeof AppManageCardsRoute
  AppNetworksRoute: typeof AppNetworksRouteWithChildren
  AppPackagesRoute: typeof AppPackagesRoute
  AppRequestsRoute: typeof AppRequestsRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentAccountsRoute: AppAgentAccountsRoute,
  AppAgentsRoute: AppAgentsRoute,
  AppCabinRoute: AppCabinRoute,
  AppCardsRoute: AppCardsRoute,
  AppJoinRequestsRoute: AppJoinRequestsRoute,
  AppLogsRoute: AppLogsRoute,
  AppManageCardsRoute: AppManageCardsRoute,
  AppNetworksRoute: AppNetworksRouteWithChildren,
  AppPackagesRoute: AppPackagesRoute,
  AppRequestsRoute: AppRequestsRoute,
  AppSalesRoute: AppSalesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
